apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: mycontainer
          image: panchanandevops/myexpress:v0.1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 3000
